### ISSUE TITLE
Unable to Program the cloud-side certs with the crt extension

### ISSUE THREAD

**Issue by rmptxf** [JeffreyUrban/nRF9160-google_iot_mqtt#3]
Hello Jeff, 
Thanks a lot for sharing this project example.
I had an issue with programming the cloud side certificates with the **.crt** extension. This command throws an error (file not found).
```
python3 cred.py \
  --CA_cert gtsltsr.pem \
  --sec_tag 202
```
I tried converting it to a **.pem** certificate, the **cred** utility programs it but its tag looks empty when looking for it in the Certificate Manager (nRF Connect App).

<img width="612" alt="empty_certs" src="https://user-images.githubusercontent.com/65089074/147285855-db0d64db-a999-4a0f-8572-7b9b0157201d.PNG">

Thanks again

**Comment by JeffreyUrban** [comment]
@rmptxf thanks for pointing out this issue. 
The README.rst was missing a step to convert the cloud-side certs from .crt to .pem. I added the missing step.

**Comment by JeffreyUrban** [comment]
@rmptxf  The cred utility is convenient, but I've found that it doesn't appear to check the format of the credentials, and just programs whatever file content is provided. 

For more meaningful feedback for troubleshooting certs, I recommend to program the device with the [nRF9160: Serial LTE modem](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/applications/serial_lte_modem/README.html) application and then [use the nRF Connect LTE Link Monitor to program the credentials](https://infocenter.nordicsemi.com/topic/ug_link_monitor/UG/link_monitor/lm_certificate_manager.html).

**Comment by rmptxf** [comment]
Thanks a lot @JeffreyUrban for your reply and the fix.
I've managed to convert both .crt certifications and used LTE Link Monitor to program them. But still the tags 202 and 203 showing 0000's, is that normal?
<img width="565" alt="certifications_tags" src="https://user-images.githubusercontent.com/65089074/147364530-8610b65a-aa32-4d0a-9683-49d0ce23301f.PNG">
The applications still can't connect, reporting a timeout error (-116) at the mqtt connect function.
<img width="549" alt="app_cant_connect" src="https://user-images.githubusercontent.com/65089074/147364533-29e144d5-5550-4dcf-a394-52d19e6198bd.PNG">

**Comment by rmptxf** [comment]
Never mind, that looks to be an issue with the SIM card used. Now it is working good!
Thanks again for the project. It was really helpful!
